version: '3.8'

services:
  file-distribution-server:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - SECRET_KEY=changeme-in-production
    restart: always
 