version: '3.8'

services:
  file-distribution-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"  # Only expose to localhost for production with reverse proxy
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-6cbca500e7e3ce4f1b70d7c7c1272fc9}  # Use environment variable if available
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/auth/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
